package views;

import utils.NotifyToast;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;


public class JdialogHangChoHD extends javax.swing.JDialog {

    private final ArrayList<Object[]> dsHDCho;
    private final DefaultTableModel modelHD;
    private Object[] user;

    /**
     * Creates new form JdialogHangChoHD
     * @param parent
     * @param modal
     * @param dsHDCho
     */
    public JdialogHangChoHD(java.awt.Frame parent, boolean modal, ArrayList<Object[]> dsHDCho) {
        super(parent, modal);
        initComponents();
        this.setLocationRelativeTo(null);
        this.dsHDCho = dsHDCho;
        modelHD = (DefaultTableModel) tbl_dsHDCho.getModel();
        renderToView();
    }

    private void renderToView() {
        for (Object[] o : dsHDCho) {
            String ten = (String) o[0];
            String sdt = (String) o[1];
            modelHD.addRow(new Object[]{ten, sdt});
        }
    }

    public Object[] getUser() {
        return user;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        scr_main = new javax.swing.JScrollPane();
        tbl_dsHDCho = new javax.swing.JTable();
        btn_thoat = new javax.swing.JButton();
        btn_tiepTuc = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentHidden(java.awt.event.ComponentEvent evt) {
                formComponentHidden(evt);
            }
        });

        scr_main.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Danh sách hóa đơn chờ", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 14))); // NOI18N

        tbl_dsHDCho.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        tbl_dsHDCho.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Tên khách hàng", "Số điện thoại"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tbl_dsHDCho.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl_dsHDChoMouseClicked(evt);
            }
        });
        scr_main.setViewportView(tbl_dsHDCho);

        btn_thoat.setText("Thoát");
        btn_thoat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_thoatActionPerformed(evt);
            }
        });

        btn_tiepTuc.setText("Tiếp tục");
        btn_tiepTuc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_tiepTucActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(scr_main, javax.swing.GroupLayout.DEFAULT_SIZE, 493, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btn_thoat)
                        .addGap(18, 18, 18)
                        .addComponent(btn_tiepTuc)
                        .addGap(15, 15, 15))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(scr_main, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn_tiepTuc, javax.swing.GroupLayout.DEFAULT_SIZE, 36, Short.MAX_VALUE)
                    .addComponent(btn_thoat, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_thoatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_thoatActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_btn_thoatActionPerformed

    private void btn_tiepTucActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_tiepTucActionPerformed
        // TODO add your handling code here:
        int selectedRow = tbl_dsHDCho.getSelectedRow();
        if (selectedRow != -1) {
            String hoTen = (String) tbl_dsHDCho.getValueAt(selectedRow, 0);
            String SDT = (String) tbl_dsHDCho.getValueAt(selectedRow, 1);
            user = new Object[]{hoTen, SDT};
            dispose();
        } else
            NotifyToast.showErrorToast("Hãy chọn hóa đơn cần thanh toán");
    }//GEN-LAST:event_btn_tiepTucActionPerformed

    private void formComponentHidden(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentHidden
        // TODO add your handling code here:
    }//GEN-LAST:event_formComponentHidden

    private void tbl_dsHDChoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_dsHDChoMouseClicked
        // TODO add your handling code here:
        if (evt.getClickCount() == 2) {
            int selectedRow = tbl_dsHDCho.getSelectedRow();
            if (selectedRow != -1) {
                String hoTen = (String) tbl_dsHDCho.getValueAt(selectedRow, 0);
                String SDT = (String) tbl_dsHDCho.getValueAt(selectedRow, 1);
                user = new Object[]{hoTen, SDT};
                dispose();
            } else {
                NotifyToast.showErrorToast("Hãy chọn hóa đơn cần thanh toán");
            }
        }
    }//GEN-LAST:event_tbl_dsHDChoMouseClicked

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_thoat;
    private javax.swing.JButton btn_tiepTuc;
    private javax.swing.JScrollPane scr_main;
    private javax.swing.JTable tbl_dsHDCho;
    // End of variables declaration//GEN-END:variables
}
