package views;

public class panel_TrangChu extends javax.swing.JPanel {

    /**
     * Creates new form panel_TrangChu
     */
    public panel_TrangChu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblLogo = new javax.swing.JLabel();
        lblNen = new javax.swing.JLabel();

        setLayout(new java.awt.BorderLayout());

        lblLogo.setBackground(new java.awt.Color(255, 255, 255));
        lblLogo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblLogo.setIcon(new javax.swing.ImageIcon("src/main/java/img/bg-small.jpg")); // NOI18N
        lblLogo.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        lblLogo.setOpaque(true);
        lblLogo.setPreferredSize(new java.awt.Dimension(400, 140));
        add(lblLogo, java.awt.BorderLayout.PAGE_START);

        lblNen.setIcon(new javax.swing.ImageIcon("src/main/java/img/bg-large.jpg")); // NOI18N
        add(lblNen, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lblLogo;
    private javax.swing.JLabel lblNen;
    // End of variables declaration//GEN-END:variables
}
